# Generated by Django 5.2.6 on 2025-10-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
