# Generated by Django 5.2.6 on 2025-11-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_department_studentid_subject_receipe_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_name'], 'verbose_name': 'student'},
        ),
        migrations.AlterUniqueTogether(
            name='subjectmarks',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subjectmarks',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjectmarks',
            name='max_marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='receipe_view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RemoveField(
            model_name='subjectmarks',
            name='marks_obtained',
        ),
    ]
